---
- name: "Availability test"
  become: true
  hosts: prod
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: "Test"
      uri:
        url: "http://{{ ansible_host }}"
        return_content: true
      register: this
      failed_when: "'Hello universe' not in this.content"
...
